MODEL:
  META_ARCHITECTURE: "SOLOv2"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  SOLOV2:
    FPN_SCALE_RANGES: "((1,72),(72,144),(144,288),(288,584),(584,2048))"
    NUM_GRIDS: "80,64,32,24,12"
    PROMPT: "point"
    NMS_TYPE: "mask"
    LOSS:
      DICE_WEIGHT: 3.0
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 16
  WARMUP_FACTOR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  BASE_LR: 0.05
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 3000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: "bitmask"
VERSION: 2