_BASE_: "Base-SOLOv2.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  SOLOV2:
    FPN_SCALE_RANGES: "((1,72),(72,144),(144,288),(288,584),(584,2048))"
    NUM_GRIDS: "80,64,32,24,12"
    PROMPT: "point"
    NMS_TYPE: "mask"
    LOSS:
      DICE_WEIGHT: 3.0
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  BASE_LR: 0.05
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 3000
TEST:
  EVAL_PERIOD: 5000
